CREATE OR REPLACE PROCEDURE delete_centro
IS
  V_NOMBRE CENTRO.NOMBRE%TYPE;
BEGIN
  SELECT NOMBRE INTO V_NOMBRE
  FROM CENTROS
  WHERE UPPER(NOMBRE)='ABRERA';
  
  IF SQL%FOUND THEN 
  DELETE FROM CENTROS WHERE UPPER(NOMBRE)='EGIBIDE';
  COMMIT;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('Imposible eliminar centro, no existe');
  
  WHEN TOO_MANY_ROWS THEN
      DBMS_OUTPUT.PUT_LINE('Hay mas de un centro con ese nombre');
END;

EXECUTE delete_centro;