CREATE OR REPLACE PROCEDURE insert_centro
IS 
  V_NOMBRE CENTROS.NOMBRE%TYPE;
BEGIN
  SELECT NOMBRE INTO V_NOMBRE
        FROM CENTROS
        WHERE UPPER(NOMBRE)='EGIBIDE';
  IF SQL%FOUND THEN DBMS_OUTPUT.PUT_LINE('Ya hay un centro con ese nombre');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  INSERT INTO CENTROS(NOMBRE, PROVINCIA) VALUES('Egibide', 'Alava');  
  IF SQL%NOTFOUND
  THEN
      DBMS_OUTPUT.PUT_LINE('Ningun registro');
  ELSE
      DBMS_OUTPUT.PUT_LINE('Insertado el centro');
      commit;
  END IF;
WHEN TOO_MANY_ROWS THEN
      DBMS_OUTPUT.PUT_LINE('Hay mas de un centro con ese nombre');
END;

EXECUTE insert_centro;


