SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE visualizar_lista_centro
IS
CURSOR C_CENTRO IS SELECT ID, NOMBRE, CALLE, NUMERO, CP, CIUDAD, PROVINCIA, TELEFONO FROM CENTROS;
E_CENTRO_NO_ENCONTRADO EXCEPTION;
REG_CENTRO C_CENTRO %ROWTYPE;
E_MOSTRAR_CENTRO EXCEPTION;
BEGIN
  
   BEGIN
     OPEN C_CENTRO;
      LOOP
        FETCH C_CENTRO INTO REG_CENTRO;
        EXIT WHEN C_CENTRO %NOTFOUND;
      END LOOP;
      CLOSE C_CENTRO;
      IF SQL%FOUND THEN
        RAISE E_MOSTRAR_CENTRO;
      END IF;
    EXCEPTION
    WHEN NO_DATA_FOUND 
      THEN
      NULL;
    WHEN TOO_MANY_ROWS
      THEN
      RAISE_APPLICATION_ERROR('-20002','ERROR; '||SQLERRM);
  END;
  EXCEPTION
    WHEN E_MOSTRAR_CENTRO THEN
      DBMS_OUTPUT.PUT_LINE('Los datos de los centros de la base de datos son :');
      OPEN C_CENTRO;
      LOOP
        FETCH C_CENTRO INTO REG_CENTRO;
        EXIT WHEN C_CENTRO %NOTFOUND;
      END LOOP;
      CLOSE C_CENTRO;
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('Error al mostrar los datos de los centros');
    WHEN E_CENTRO_NO_ENCONTRADO then
      RAISE_APPLICATION_ERROR ('-20003','ERR. id no encontrado');
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR ('-20003','ERROR: ' || SQLERRM);
  
END;

EXECUTE visualizar_lista_centro;

SELECT * FROM CENTROS;